// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: api/user/v1/error_code.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_CREATE_ANONYMOUS_USER_FAILED ErrorCode = 0
	ErrorCode_TOKEN_INVALID                ErrorCode = 1
	ErrorCode_USER_NOT_FOUND               ErrorCode = 2
	ErrorCode_REFRESH_TOKEN_INVALID        ErrorCode = 3
	ErrorCode_REFRESH_TOKEN_MISS_MATCH     ErrorCode = 4
	ErrorCode_GENERATE_TOKEN_FAILED        ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "CREATE_ANONYMOUS_USER_FAILED",
		1: "TOKEN_INVALID",
		2: "USER_NOT_FOUND",
		3: "REFRESH_TOKEN_INVALID",
		4: "REFRESH_TOKEN_MISS_MATCH",
		5: "GENERATE_TOKEN_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"CREATE_ANONYMOUS_USER_FAILED": 0,
		"TOKEN_INVALID":                1,
		"USER_NOT_FOUND":               2,
		"REFRESH_TOKEN_INVALID":        3,
		"REFRESH_TOKEN_MISS_MATCH":     4,
		"GENERATE_TOKEN_FAILED":        5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_v1_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_user_v1_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_user_v1_error_code_proto_rawDescGZIP(), []int{0}
}

var File_api_user_v1_error_code_proto protoreflect.FileDescriptor

var file_api_user_v1_error_code_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2a, 0xa8, 0x01, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x5f, 0x41, 0x4e, 0x4f, 0x4e, 0x59, 0x4d, 0x4f, 0x55, 0x53, 0x5f, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54,
	0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x46, 0x52, 0x45, 0x53, 0x48, 0x5f, 0x54, 0x4f,
	0x4b, 0x45, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x03, 0x12, 0x1c, 0x0a,
	0x18, 0x52, 0x45, 0x46, 0x52, 0x45, 0x53, 0x48, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x4d,
	0x49, 0x53, 0x53, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x47,
	0x45, 0x4e, 0x45, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x42, 0x2a, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x19, 0x62, 0x69, 0x62, 0x69, 0x72, 0x74, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_user_v1_error_code_proto_rawDescOnce sync.Once
	file_api_user_v1_error_code_proto_rawDescData = file_api_user_v1_error_code_proto_rawDesc
)

func file_api_user_v1_error_code_proto_rawDescGZIP() []byte {
	file_api_user_v1_error_code_proto_rawDescOnce.Do(func() {
		file_api_user_v1_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_v1_error_code_proto_rawDescData)
	})
	return file_api_user_v1_error_code_proto_rawDescData
}

var file_api_user_v1_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_v1_error_code_proto_goTypes = []interface{}{
	(ErrorCode)(0), // 0: api.user.v1.ErrorCode
}
var file_api_user_v1_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_v1_error_code_proto_init() }
func file_api_user_v1_error_code_proto_init() {
	if File_api_user_v1_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_v1_error_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_v1_error_code_proto_goTypes,
		DependencyIndexes: file_api_user_v1_error_code_proto_depIdxs,
		EnumInfos:         file_api_user_v1_error_code_proto_enumTypes,
	}.Build()
	File_api_user_v1_error_code_proto = out.File
	file_api_user_v1_error_code_proto_rawDesc = nil
	file_api_user_v1_error_code_proto_goTypes = nil
	file_api_user_v1_error_code_proto_depIdxs = nil
}
