CREATE TABLE `users` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`uuid` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_bin',
	`type` TINYINT(3) UNSIGNED NOT NULL,
	`phone` CHAR(11) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`password` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`name` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	`salt` CHAR(8) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`status` TINYINT(3) UNSIGNED NOT NULL,
	`created_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`updated_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='用户表'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;
