// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bibirt-api/internal/data/ent/schema"
	"bibirt-api/internal/data/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescScore is the schema descriptor for score field.
	userDescScore := userFields[7].Descriptor()
	// user.DefaultScore holds the default value on creation for the score field.
	user.DefaultScore = userDescScore.Default.(uint64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
